# Generated by Django 4.2 on 2023-05-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='photo',
            new_name='image',
        ),
    ]
