# Generated by Django 4.2 on 2023-05-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_photo_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='creation_date',
        ),
    ]
