# Generated by Django 4.2 on 2023-05-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
