# Generated by Django 4.2 on 2023-05-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('work', 'Work'), ('unknow', 'Unknow')], default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
