# Generated by Django 4.2 on 2023-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('work', 'Work'), ('unknow', 'Unknow')], default='family', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='default', max_length=254, unique=True),
        ),
    ]
